version: '3'
services:
  # mongo
  mongo:
    image: mongo:latest
    container_name: mongo # docker启动后的名称
    network_mode: host
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/data/mongo/data/configdb:/data/configdb
      - ~/data/mongo/data/db:/data/db
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    network_mode: host
    restart: always
    ports:
      - 8848:8848
    environment:
      - MODE=standalone #启动模式是独立模式
      - PREFER_HOST_MODE=hostname
    volumes:
      - ./config/nacos/custom.properties:/home/nacos/init.d/custom.properties
  elasticsearch:
    image: elasticsearch:6.8.0
    container_name: elasticsearch
    restart: always
    network_mode: host
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ~/data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  skywalking-oap:
    image: apache/skywalking-oap-server:6.1.0
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 192.168.56.200:9200
    volumes:
      - ./config/skywalking/oap/application.yml:/skywalking/config/application.yml
  skywalking-ui:
    image: apache/skywalking-ui:6.1.0
    container_name: skywalking-ui
    depends_on:
      - "skywalking-oap"
    restart: always
    ports:
      - 18080:8080
    environment:
      collector.ribbon.listOfServers: 192.168.56.200:12800
      security.user.admin.password: admin123