spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: io.github.sunny.cherry.tomato.account.service
  protocol:
    name: dubbo
    port: 20885