#spring:
#  application:
#    name: @project.artifactId@
#  profiles:
#    active: local
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#dubbo:
#  registry:
#    address: spring-cloud://localhost:8848
#  scan:
#    base-packages: io.github.sunny.cherry.tomato
#  protocol:
#    name: dubbo
#    port: -1
##  registry:
##    address: nacos://127.0.0.1:8848
##    host: 192.168.3.20