spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: io.github.sunny.cherry.tomato.cache.service
  protocol:
    name: dubbo
    port: -1
