spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://192.168.56.200:27017/cherry
dubbo:
  scan:
    base-packages: io.github.sunny.cherry.tomato.account.service
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://192.168.56.200:8848

cherry:
  dingtalk:
    corp-id: dingfe5fc7deb96c399e35c2f4657eb6378f
    app-key: dingsdw3uhysirwbmbxo
    app-secret: EwFdJTI19hZzQVsufGcvMNsub_YZ1JOJQ7Si-nAdRMJbIA_4T8yvfrvuA7E1N6CA
    agent-id: 333388984
    callback-url: http://ff104fa7.ngrok.io/api/dingtalk/microapp/callback
    token: 123456 # 加解密需要用到的token，ISV(服务提供商)推荐使用注册套件时填写的token，普通企业可以随机填写
    aes-key: abcdefghijabcdefghijabcdefghijabcdefghij123
    call-back-tag:
      - user_add_org # 通讯录用户增加
      - user_modify_org # 通讯录用户更改
      - user_leave_org # 通讯录用户离职
      - user_active_org # 加入企业后用户激活
      - org_admin_add # 通讯录用户被设为管理员
      - org_admin_remove # 通讯录用户被取消设置管理员
      - org_dept_create # 通讯录企业部门创建
      - org_dept_modify # 通讯录企业部门修改
      - org_dept_remove # 通讯录企业部门删除
      - org_remove # 企业被解散
      - org_change # 企业信息发生变更
      - label_user_change # 员工角色信息发生变更
      - label_conf_add # 增加角色或者角色组
      - label_conf_del # 删除角色或者角色组
      - label_conf_modify # 修改角色或者角色组
      - chat_add_member # 群会话添加人员
      - chat_remove_member # 群会话删除人员
      - chat_quit # 群会话用户主动退群
      - chat_update_owner # 群会话更换群主
      - chat_update_title # 群会话更换群名称
      - chat_disband # 群会话解散群