server:
  port: 8100
spring:
  application:
    name: cherry-tomato
  profiles:
    active: local
#  redis:
#    database: 13
#    host: 192.168.200.22
#    port: 30044
#    password: Bn3oNpnuAO2yM9B8yciM



