#redis:
#  database: 13
#  host: 192.168.200.22
#  port: 30044
#  password: Bn3oNpnuAO2yM9B8yciM

server:
  port: 8100
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: io.github.sunny.cherry.tomato.controller
  cloud:
    subscribed-services: cherry-tomato-cache-server
  protocol:
    name: dubbo
    port: 20879
#    host: 192.168.3.20
  consumer:
    check: false
