#redis:
#  database: 13
#  host: 192.168.200.22
#  port: 30044
#  password: Bn3oNpnuAO2yM9B8yciM

server:
  port: 8100
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: io.github.sunny.cherry.tomato.controller
